// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changingGenreGenreNametoGenreName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changingGenreGenreNametoGenreName));
        
        string IMigrationMetadata.Id
        {
            get { return "201704272200141_changing Genre.GenreName to Genre.Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
